-- Sample data covering every table in db/schema.sql.
-- Assumes a clean DB (run db/reset.sql then db/schema.sql first) so that
-- GENERATED ALWAYS AS IDENTITY produces predictable IDs starting at 1.

-- Caterers → IDs 1..4
-- chef_email left NULL where the contact is also the chef (single point of contact).
INSERT INTO caterers (name, region, contact_email, chef_email, cc_chef) VALUES
    ('Lakehouse Victoria Point', 'Redlands',         'orders@lakehousevp.com.au',  'chef@lakehousevp.com.au', TRUE),
    ('Terrific Noodles',         'South Brisbane',   'hello@terrificnoodles.com',  NULL,                      FALSE),
    ('Kenko Sushi House',        'West Brisbane',    'orders@kenkosushi.com.au',   'kitchen@kenkosushi.com.au', TRUE),
    ('Guzman y Gomez',           'Central Brisbane', 'catering@gyg.com.au',        NULL,                      FALSE);

-- Pricing structures (1:1 with caterers)
INSERT INTO pricing_structures (caterer_id, price_per_item, per_trip_fee, per_school_per_trip_fee) VALUES
    (1, 35.00, 0,     0),
    (2, 20.50, 0,     30.00),
    (3,  5.50, 0,     10.00),
    (4, 15.00, 50.00, 0);

-- Menu items. Source menus use VO ("vegetarian option") to mean the dish can be
-- prepared either way; each such item is split into a non-veg row and a (Vegetarian) row.
INSERT INTO items (caterer_id, name, dietary_tags) VALUES
    (1, 'Shrimp Fried Rice',                                '{GF,DF,H}'),
    (1, 'Spaghetti Bolognese + Garlic Bread',               '{NF,H}'),
    (1, 'Sweet and Sour Chicken',                           '{GF,DF,NF,H}'),
    (1, 'Japanese Chicken Curry',                           '{DF,NF,H}'),
    (1, 'Japanese Chicken Curry (Vegetarian)',              '{DF,NF,V,H}'),
    (2, 'Spicy Miso Udon',                                  '{DF,H}'),
    (2, 'Mie Goreng',                                       '{GF,DF,NF,H}'),
    (2, 'Mie Goreng (Vegetarian)',                          '{GF,DF,NF,V,H}'),
    (2, 'Beef Pad Thai',                                    '{H}'),
    (2, 'Lemongrass Grilled Beef and Noodles',              '{GF,DF,NF,H}'),
    (2, 'Lemongrass Grilled Beef and Noodles (Vegetarian)', '{GF,DF,NF,V,H}'),
    (3, 'Teriyaki Salmon rice bowl',                        '{GF,DF,NF,H}'),
    (3, 'Teriyaki Salmon rice bowl (Vegetarian)',           '{GF,DF,NF,V,H}'),
    (3, 'Chicken Karaage ricebowl',                         '{DF,NF,H}'),
    (3, 'Chicken Karaage ricebowl (Vegetarian)',            '{DF,NF,V,H}'),
    (3, 'Sweet and Sour Chicken',                           '{GF,DF,H}'),
    (4, 'Caesar Salad',                                     '{GF,DF,NF,H}'),
    (4, 'Caesar Salad (Vegetarian)',                        '{GF,DF,NF,V,H}'),
    (4, 'Chicken Enchilada',                                '{GF,DF,H}'),
    (4, 'Nachos',                                           '{GF,H}'),
    (4, 'Nachos (Vegetarian)',                              '{GF,V,H}'),
    (4, 'Pulled pork burrito bowl',                         '{GF,NF}'),
    (4, 'Pulled pork burrito bowl (Vegetarian)',            '{GF,NF,V,H}');

-- Feedback (manager-submitted notes about caterers).
-- 15 entries per caterer, written across the term as if the manager knows an LLM will
-- mine them for per-dish quality signals. Dollar-quoted strings ($$...$$) avoid the
-- need to escape apostrophes inside the prose.
INSERT INTO feedback (caterer_id, submitted_at, content) VALUES
    (1, '2026-02-10 19:30+10', $$The Spaghetti Bolognese was a clear crowd favourite tonight — generous beef portion and the garlic bread was warm and crisp on the bottom. Sauce had good depth, a little salty but no one complained. Shrimp Fried Rice was lukewarm by the time the third Year 12 reached the front of the line. Considering pre-portioning into trays rather than serving from a single dish. Vegetarian curry sat untouched for 10 minutes before anyone took one.$$),
    (1, '2026-02-17 19:30+10', $$Strong night overall. The Japanese Chicken Curry was the standout — chicken was tender, the sauce was rich without being too thick, and the rice portion was right-sized. Sweet and Sour Chicken was crunchy out of the box but went soggy quickly, probably due to sauce-on-rice plating. Garlic bread on the Spaghetti Bolognese was a bit pale, could use another minute under the grill. Triet noted multiple seconds requests for the Japanese Chicken Curry.$$),
    (1, '2026-02-24 19:30+10', $$Service ran smoothly. Shrimp Fried Rice was much improved — kept warm in foil trays, portions were even. Sweet and Sour Chicken was slightly oversauced tonight, a few students set the sauce aside. The Japanese Chicken Curry (Vegetarian) lacked the depth of the non-veg version; tofu and vegetables tasted under-seasoned. Spaghetti Bolognese arrived on time, well-portioned. Two students said the garlic bread was the best so far this term.$$),
    (1, '2026-03-03 19:30+10', $$Delivery was 12 minutes late, ate into our dinner window. Shrimp Fried Rice came out cold and we had to microwave half the trays, which dried them out. Japanese Chicken Curry held heat better — texture and flavour both held up well. The non-vegetarian Japanese Chicken Curry continues to be the most reliable item from Lakehouse. Sweet and Sour Chicken portions felt smaller than usual, perhaps half a cup short per serve.$$),
    (1, '2026-03-10 19:30+10', $$Spaghetti Bolognese was excellent — the sauce was the thickest yet and the beef-to-pasta ratio was on point. Garlic bread well-toasted. Sweet and Sour Chicken sauce was too sweet tonight, almost dessert-like; Year 11s loved it, Year 12s less so. Japanese Chicken Curry (Vegetarian) portions were tiny compared to non-veg ones — only two students opted in but both finished quickly and asked if there was more.$$),
    (1, '2026-03-17 19:30+10', $$Quiet feedback night. Japanese Chicken Curry steady as always — well-portioned, well-spiced, students happy. Shrimp Fried Rice slightly oily, some students mentioned a noticeable shrimp smell from the trays. Worth Lakehouse checking ingredient freshness on the seafood side. Spaghetti Bolognese was solid but the garlic bread was hard and stale-tasting, suggesting it was made earlier in the day. Nothing wrong with the Japanese Chicken Curry (Vegetarian) tonight.$$),
    (1, '2026-03-24 19:30+10', $$Sweet and Sour Chicken was the surprise hit tonight. Sauce had a sharper, more balanced tang than previous weeks. The non-veg Japanese Chicken Curry was also great. Shrimp Fried Rice was decent but a few students found a piece of shell in their portion — please reinforce the shell check during prep. Japanese Chicken Curry (Vegetarian) was barely touched again; might be worth dropping it next term unless specifically requested.$$),
    (1, '2026-03-31 19:30+10', $$Delivery exactly on time. Spaghetti Bolognese was great, the garlic bread improved over recent weeks. Japanese Chicken Curry was the slowest mover tonight — students said the spice level was higher than usual, possibly off-recipe. Two students gave up halfway through. Sweet and Sour Chicken was solid. Shrimp Fried Rice arrived warm and well-portioned. Lakehouse should standardise the curry recipe more tightly — variability is a recurring theme.$$),
    (1, '2026-04-07 19:30+10', $$The Japanese Chicken Curry (Vegetarian) was noticeably better tonight — the tofu was firm, the carrots and peas were just-cooked, and the sauce was not as bland as past weeks. The non-veg Japanese Chicken Curry was good as always. Spaghetti Bolognese was over-portioned and several students left meatballs and pasta on the plate. Garlic bread was perfect. Shrimp Fried Rice was lukewarm again — heat management is becoming the main complaint.$$),
    (1, '2026-04-14 19:30+10', $$Sweet and Sour Chicken sauce was too thin tonight, ran off the chicken. Otherwise the chicken itself was tender. Spaghetti Bolognese was the best in weeks — clearly a different mince batch, much richer. Both Japanese Chicken Curry versions were solid. Shrimp Fried Rice tasted different tonight, more like a garlic prawn rice — colour and aroma both shifted. Worth confirming with Lakehouse whether they swapped the recipe.$$),
    (1, '2026-04-21 19:30+10', $$Big night, six servings of Japanese Chicken Curry between Year 11 and 12. Chicken was beautifully tender, sauce well-balanced. Spaghetti Bolognese was over-salted; multiple students reached for water. Garlic bread was good. Japanese Chicken Curry (Vegetarian) was finally hot through the middle — past weeks the centre has been cooler than the edges. Sweet and Sour Chicken untouched by half the orderers tonight, served too oily.$$),
    (1, '2026-04-28 19:30+10', $$Shrimp Fried Rice was back to its usual character — clean prawn flavour, no off-smell. Japanese Chicken Curry was excellent, possibly the best portion size we have had. Spaghetti Bolognese was undercooked tonight, the pasta had a chalky core. Garlic bread compensated. Sweet and Sour Chicken sauce was right-balanced. Worth flagging the pasta consistency back to Lakehouse — second time this term we have seen the pasta al-dente verging on raw.$$),
    (1, '2026-05-05 19:30+10', $$Solid all-round night. Japanese Chicken Curry was reliable as ever — Year 12s consistently pick it first. The vegetarian version was also fine, no complaints. Sweet and Sour Chicken had a deeper colour and richer sauce than usual, students enjoyed it. Spaghetti Bolognese was on the dry side, sauce-to-pasta ratio tilted too much toward pasta. Garlic bread was good. Shrimp Fried Rice was the lowest-pick item again tonight.$$),
    (1, '2026-05-12 19:30+10', $$Strong night for the curries. Both Japanese Chicken Curry versions had excellent texture and seasoning. Sweet and Sour Chicken was great, especially the breading — crispy and held its crunch through serving. Spaghetti Bolognese was over-portioned and the bolognese sauce had a slightly burnt aftertaste. Garlic bread saved it. Shrimp Fried Rice tasted faintly sour — possibly an older rice batch. Recommend Lakehouse review their stock rotation.$$),
    (1, '2026-05-19 19:30+10', $$Best night of the term. Japanese Chicken Curry was extraordinary tonight — chicken practically melted, sauce was deep and savoury. Japanese Chicken Curry (Vegetarian) was equally good. Sweet and Sour Chicken was crisp and well-sauced. Spaghetti Bolognese was excellent — generous portion, rich sauce, garlic bread perfectly golden. Shrimp Fried Rice was the only weak point, dry and slightly cold by service time. Overall a high-water mark we would happily reorder against.$$),

    (2, '2026-02-10 19:50+10', $$The Spicy Miso Udon was the dish of the night — broth had real depth, the noodles held bite, and the chilli was present but not overwhelming. Mie Goreng was solid, the chicken pieces tender and well-coated in sauce. The Mie Goreng (Vegetarian) was a touch under-seasoned compared to the non-veg version, which is a recurring pattern. Beef Pad Thai arrived a little oily but the flavour was good. Strong opener for Terrific Noodles this term.$$),
    (2, '2026-02-17 19:50+10', $$Lemongrass Grilled Beef and Noodles was excellent — beef was charred just right, lemongrass came through clearly, noodles cool but the dressing brought it together. Mie Goreng (Vegetarian) was bland tonight, soy-heavy without the aromatic balance. Spicy Miso Udon was great. Beef Pad Thai was a bit dry, peanuts on top compensated. Jessie noted students reaching for the Lemongrass Grilled Beef first when the trays were uncovered.$$),
    (2, '2026-02-24 19:50+10', $$Tonight Beef Pad Thai was outstanding — moister than past weeks, beef well-seared, tamarind sweetness balanced with lime. Mie Goreng was its usual reliable self. Lemongrass Grilled Beef and Noodles (Vegetarian) continues to be the weakest item — replacing the beef with tofu drains the dish of its main flavour anchor. Spicy Miso Udon went cold by the time we served the back of the line, packaging insulation is suboptimal.$$),
    (2, '2026-03-03 19:50+10', $$Mie Goreng was on form — sauce was caramelised properly, the noodles had wok hei character. Spicy Miso Udon broth was thinner than usual, almost watery, suggests the stock was diluted. Lemongrass Grilled Beef and Noodles came out cold tonight and the lemongrass aroma had dulled. Beef Pad Thai was crunchy and bright — peanuts and bean sprouts at peak. Mie Goreng (Vegetarian) was better than past weeks; flavour gap to non-veg is narrowing.$$),
    (2, '2026-03-10 19:50+10', $$Strong night. Spicy Miso Udon was back to its full broth depth, students lined up for it. Lemongrass Grilled Beef and Noodles both versions were good — the vegetarian had marinated mushrooms that held flavour well. Mie Goreng was a touch over-spicy tonight, a few Year 9s asked for water. Beef Pad Thai was excellent — generous beef portion, fresh herbs. Best vegetarian variety we have seen from Terrific Noodles this term.$$),
    (2, '2026-03-17 19:50+10', $$Off night for Beef Pad Thai — the noodles clumped, sauce had pooled at the bottom of the container. Beef itself was fine. Mie Goreng and Mie Goreng (Vegetarian) were both well-executed. Spicy Miso Udon was solid. Lemongrass Grilled Beef and Noodles (Vegetarian) came with too little dressing, was quite dry; non-veg fine. Heat retention is the recurring complaint — almost everything served lukewarm tonight.$$),
    (2, '2026-03-24 19:50+10', $$Spicy Miso Udon was very good tonight — broth flavoursome, noodles springy. Mie Goreng portions were generous but the noodles had clumped. Beef Pad Thai had excellent fresh herbs but the beef was overcooked, tough in spots. Lemongrass Grilled Beef and Noodles (non-veg) was the best dish of the night — marinade clearly applied longer, deep aroma. Lemongrass Grilled Beef and Noodles (Vegetarian) was under-seasoned. Vegetarian gap remains.$$),
    (2, '2026-03-31 19:50+10', $$Quiet night, only 12 catered. Beef Pad Thai was on form again — moist, flavoursome, beef tender. Mie Goreng was good. Spicy Miso Udon was the most picked item; broth quality has stabilised at a consistently high level. Lemongrass Grilled Beef and Noodles non-veg was great. Lemongrass Grilled Beef and Noodles (Vegetarian) continues to be the weakest item on the menu. Worth Terrific Noodles rethinking their tofu marinade specifically.$$),
    (2, '2026-04-07 19:50+10', $$Mie Goreng arrived overcooked tonight, noodles slightly mushy and over-sauced. The Mie Goreng (Vegetarian) was actually better than the non-veg in this batch — drier and more textured. Spicy Miso Udon great as always. Beef Pad Thai had clumped again. Lemongrass Grilled Beef and Noodles was excellent. Generally the udon and lemongrass beef are the strongest items week-on-week; Pad Thai is hit-or-miss depending on packaging.$$),
    (2, '2026-04-14 19:50+10', $$Lemongrass Grilled Beef and Noodles (Vegetarian) was finally good — tofu had grill marks and lemongrass aroma was present. Non-veg was equally strong. Spicy Miso Udon had thinner-than-usual broth again. Beef Pad Thai was tonight standout — crunchy peanuts, well-cooked beef, sauce balanced. Mie Goreng both versions reliable. Overall a high-quality night with mostly even execution across items.$$),
    (2, '2026-04-21 19:50+10', $$Service was rushed because of late delivery. Spicy Miso Udon held heat well thanks to the lidded bowls. Mie Goreng was overcooked from sitting too long. Beef Pad Thai was decent. Lemongrass Grilled Beef and Noodles both versions arrived at room temperature, the marinade flavour was muted. Mie Goreng (Vegetarian) was the bright spot tonight, tofu well-seasoned and noodles still had bite. Punctuality is the issue this week.$$),
    (2, '2026-04-28 19:50+10', $$Beef Pad Thai outstanding tonight — best of the term. Beef was tender, noodles loose and well-coated, lime wedges fresh. Spicy Miso Udon was great, complaint-free. Mie Goreng was a little over-spicy for the Year 9s. Lemongrass Grilled Beef and Noodles (non-veg) was excellent. Lemongrass Grilled Beef and Noodles (Vegetarian) was the weakest — tofu was undercooked in the centre, almost cold. Pad Thai and lemongrass beef are dishes Terrific Noodles really excels at.$$),
    (2, '2026-05-05 19:50+10', $$Strong all-round night. Mie Goreng both versions were excellent — wok hei character on both, vegetarian had crisp tofu cubes. Spicy Miso Udon solid as ever. Beef Pad Thai was great, beef well-seared. Lemongrass Grilled Beef and Noodles both versions worked well. Best vegetarian execution we have seen from Terrific Noodles this entire term. Suggest sharing this week prep notes back to their kitchen so they can replicate.$$),
    (2, '2026-05-12 19:50+10', $$Spicy Miso Udon noticeably saltier tonight, several students reached for water. Mie Goreng and Beef Pad Thai were both strong — Pad Thai especially, beef tender and well-marinated. Lemongrass Grilled Beef and Noodles was good non-veg, vegetarian was bland again. Mie Goreng (Vegetarian) was the only weak item, tasted under-soyed. Heat retention much improved over earlier weeks — most dishes arrived above lukewarm.$$),
    (2, '2026-05-19 19:50+10', $$Mie Goreng was excellent both versions tonight. Spicy Miso Udon broth was at peak depth. Beef Pad Thai was perfect — moist, balanced, beef tender. Lemongrass Grilled Beef and Noodles (non-veg) was outstanding. Lemongrass Grilled Beef and Noodles (Vegetarian) was the only weak point — tofu still under-flavoured compared to the beef counterpart. Best week of the term overall. Terrific Noodles consistently excels at noodle-soup style dishes, less so at vegetarian-substituted grill items.$$),

    (3, '2026-02-09 18:50+10', $$Teriyaki Salmon rice bowl was outstanding tonight — salmon was perfectly cooked, glaze deep and balanced, rice fluffy and not sticky. Chicken Karaage ricebowl was crispy and well-portioned, the dipping sauce was a nice touch. Teriyaki Salmon rice bowl (Vegetarian) was a creative dish — marinated mushroom and tofu replacing salmon worked surprisingly well. Sweet and Sour Chicken was the weakest, sauce a touch too sweet. Kenko premium-feel packaging is a real plus.$$),
    (3, '2026-02-16 18:50+10', $$Chicken Karaage ricebowl was the dish of the night — chicken was juicy, batter crispy even after transport. Teriyaki Salmon rice bowl was good but salmon was a fraction dry in the centre, possibly overcooked. Chicken Karaage ricebowl (Vegetarian) tasted indistinguishable from the non-veg according to one student, which is high praise for the meat substitute. Sweet and Sour Chicken sauce was thicker tonight, clung well. Lucian noted students requesting the karaage twice over.$$),
    (3, '2026-02-23 18:50+10', $$Both Teriyaki Salmon rice bowl versions were excellent — fresh-tasting salmon, the vegetarian version had a smoky tofu element that students enjoyed. Sweet and Sour Chicken arrived warm. Chicken Karaage ricebowl was less crispy tonight, batter had softened in the box. Heat retention seems batch-dependent. Best overall night for vegetarian options this term — the gap between veg and non-veg dishes has narrowed considerably for Kenko.$$),
    (3, '2026-03-02 18:50+10', $$Salmon was very fresh tonight, students commented on the texture of the Teriyaki Salmon rice bowl. Sauce-to-rice ratio was right. Chicken Karaage ricebowl was crispy and the gingery dipping sauce had more kick than usual. Chicken Karaage ricebowl (Vegetarian) was excellent — the tofu was firm and held its breading. Sweet and Sour Chicken portions were small, two students asked for an extra serve. Kenko continues to deliver the most consistently high-quality protein execution of any catering partner.$$),
    (3, '2026-03-09 18:50+10', $$Off night for Kenko. Teriyaki Salmon rice bowl arrived with the rice slightly mushy, possibly over-rinsed in prep. Glaze was good. Chicken Karaage ricebowl had lost crispness by service — moisture had condensed in the box. Sweet and Sour Chicken was solid. Teriyaki Salmon rice bowl (Vegetarian) was the saving grace, tofu well-marinated and rice fine. Pricing is excellent so this off night is forgivable. Encourage Kenko to use ventilated packaging for breaded items.$$),
    (3, '2026-03-16 18:50+10', $$Strong recovery for Kenko. Chicken Karaage ricebowl was crispy and the sauce was generous. Both Teriyaki Salmon rice bowl versions were great — salmon was firm and the vegetarian tofu equivalent was well-seasoned. Sweet and Sour Chicken had a brighter sauce than usual, students enjoyed it. Rice quality was perfect across the board. Heat retention solved by Kenko switch to better-insulated boxes — this is a noticeable week-on-week improvement.$$),
    (3, '2026-03-23 18:50+10', $$Teriyaki Salmon rice bowl was outstanding — best execution this term. Salmon was thick-cut, glaze caramelised correctly, rice fluffy. Chicken Karaage ricebowl was also great, crisp and hot. Chicken Karaage ricebowl (Vegetarian) was bland tonight, the breading was not seasoned as well as previous weeks. Sweet and Sour Chicken was over-sauced, students mopped the excess off the rice. Kenko per-meal pricing remains best-in-class for the quality delivered.$$),
    (3, '2026-03-30 18:50+10', $$Sweet and Sour Chicken sauce was thinner tonight, ran off the rice. Chicken itself was tender. Both Teriyaki Salmon rice bowl versions were excellent — vegetarian had a particularly nice umami depth from the mushroom topping. Chicken Karaage ricebowl was crispy as expected. Rice was a little overcooked, sticky rather than fluffy. Overall a strong night, with the rice texture being the only minor complaint.$$),
    (3, '2026-04-06 18:50+10', $$Teriyaki Salmon rice bowl was the highlight — salmon was buttery, glaze deep, ginger garnish bright. Chicken Karaage ricebowl was outstanding for crispiness, possibly the best of the term. Sweet and Sour Chicken was reliable, sauce well-balanced. Both vegetarian versions were good, no complaints. Kenko consistency week-on-week is noticeably higher than the other caterers we use. Worth recommending them to other schools.$$),
    (3, '2026-04-13 18:50+10', $$Chicken Karaage ricebowl was excellent both versions tonight. Teriyaki Salmon rice bowl arrived cooler than usual, mid-serve temperature was lukewarm. Salmon flavour still good. Sweet and Sour Chicken was great. Teriyaki Salmon rice bowl (Vegetarian) was strong. Heat retention regressed this week — possibly a different driver or earlier prep time. Worth flagging back to Kenko. Otherwise quality was excellent across all dishes, just the temperature issue.$$),
    (3, '2026-04-20 18:50+10', $$Outstanding night. Teriyaki Salmon rice bowl was perfectly cooked and beautifully presented. Chicken Karaage ricebowl was crispy, juicy, well-portioned. Sweet and Sour Chicken sauce was bright and balanced. Both Teriyaki Salmon rice bowl (Vegetarian) and Chicken Karaage ricebowl (Vegetarian) tasted as good as their non-veg counterparts. Heat retention was back to normal. Kenko continues to set the standard for quality-to-price ratio. Students consistently rate Kenko highest on informal post-session checks.$$),
    (3, '2026-04-27 18:50+10', $$Teriyaki Salmon rice bowl was good but the rice was slightly under-cooked, grains had bite. Glaze was excellent. Chicken Karaage ricebowl was at its usual high quality. Chicken Karaage ricebowl (Vegetarian) was outstanding, breading well-seasoned. Sweet and Sour Chicken sauce was slightly too sweet tonight. Teriyaki Salmon rice bowl (Vegetarian) was solid. Worth Kenko reviewing their rice cooking time — it has wavered a few times this term between sticky and undercooked.$$),
    (3, '2026-05-04 18:50+10', $$Excellent across the board. Salmon in the Teriyaki Salmon rice bowl was buttery and perfectly cooked. Chicken Karaage ricebowl was the crispiest yet, possibly thanks to packaging ventilation improvements. Sweet and Sour Chicken was great. Both vegetarian versions were strong, no flavour gap from their non-veg counterparts. Rice was fluffy. Heat retention perfect. This is what consistency looks like — Kenko sets the benchmark for the term so far.$$),
    (3, '2026-05-11 18:50+10', $$Strong night again. Teriyaki Salmon rice bowl was excellent, vegetarian version had a particularly good mushroom-and-tofu balance. Chicken Karaage ricebowl was crispy and well-portioned. Sweet and Sour Chicken sauce was on the salty side tonight, otherwise fine. Rice was great. Heat retention very good. Three weeks of consistent quality now — Kenko is the most stable of our caterers right now.$$),
    (3, '2026-05-18 18:50+10', $$Teriyaki Salmon rice bowl was outstanding — best of the term. Salmon was thick, glaze caramelised perfectly, rice fluffy. Chicken Karaage ricebowl was crispy and the dipping sauce had kick. Sweet and Sour Chicken was solid. Both vegetarian versions were great. Heat retention perfect. Kenko closes the term strongly. They have set the bar for next term — other caterers should aim to match their consistency and presentation.$$),

    (4, '2026-02-09 18:50+10', $$Pulled pork burrito bowl was the standout — pork was tender, beans and rice well-seasoned, salsa fresh. Nachos were soggy by service time, cheese had congealed into a hard mass — the topping-on-chips packaging does not survive transit. Recommend separating sauces. Chicken Enchilada was good, cheese was stretchy and the chicken well-shredded. Caesar Salad was crisp and well-dressed. Pulled pork burrito bowl (Vegetarian) was creative — jackfruit substitute was convincing.$$),
    (4, '2026-02-16 18:50+10', $$Caesar Salad was excellent tonight — romaine was crisp, croutons were buttery, dressing was tangy without being heavy. Caesar Salad (Vegetarian) was equally good. Chicken Enchilada had a nice spice kick. Nachos arrived in the same compromised state — chips broken and topping coalesced. GYG should consider deconstructed Nachos with chips in a separate compartment. Pulled pork burrito bowl was great. Pulled pork burrito bowl (Vegetarian) was on the bland side tonight, missing smoky depth.$$),
    (4, '2026-02-23 18:50+10', $$Nachos finally arrived with chips in a side container — texture problem solved. Sauce and cheese went on top at serving and stayed crisp. Pulled pork burrito bowl was good. Caesar Salad was excellent. Chicken Enchilada was the standout, cheese was perfectly melted and the chicken was generously portioned. Both vegetarian options were solid tonight. This is what GYG looks like when packaging is sorted — quality matches the cost.$$),
    (4, '2026-03-02 18:50+10', $$Pulled pork burrito bowl was outstanding — pork was beautifully tender, salsa fresh, lime wedge bright. Pulled pork burrito bowl (Vegetarian) was almost as good — jackfruit had absorbed marinade well. Nachos delivered correctly assembled. Caesar Salad portions were small tonight, two students asked if there was more. Chicken Enchilada was solid. GYG has the highest highs but the most variable portion sizes of our caterers.$$),
    (4, '2026-03-09 18:50+10', $$Off night for portions. Caesar Salad was tiny, basically a side dish. Nachos and Pulled pork burrito bowl were correctly portioned. Chicken Enchilada arrived lukewarm, cheese had stiffened. Nachos (Vegetarian) were on point. Pulled pork burrito bowl (Vegetarian) was bland again, this is becoming a recurring complaint — the jackfruit needs heavier seasoning to match the non-veg version. GYG should standardise portion sizes more carefully.$$),
    (4, '2026-03-16 18:50+10', $$Chicken Enchilada was excellent — hot, cheesy, well-spiced. Nachos came correctly assembled with chips and toppings separate. Pulled pork burrito bowl both versions were good, the vegetarian noticeably improved with smokier seasoning. Caesar Salad was perfect — crisp, generous portion. GYG quality is highest when portion size is consistent. Pricing remains a concern — students notice when they are paying for less food than the listed price suggests.$$),
    (4, '2026-03-23 18:50+10', $$Pulled pork burrito bowl was outstanding tonight — best of the term. Pork was fall-apart tender, rice fluffy, salsa bright. Nachos were perfect. Chicken Enchilada was good. Caesar Salad arrived limp tonight, dressing had been applied too early and the romaine had wilted. Pulled pork burrito bowl (Vegetarian) was much closer to non-veg quality. Best overall night for GYG so far, salad notwithstanding.$$),
    (4, '2026-03-30 18:50+10', $$Nachos were soggy again — packaging slipped back to the old format. Toppings on chips, chips lost crunch. Caesar Salad was good. Chicken Enchilada was excellent, cheese was stringy and well-melted. Pulled pork burrito bowl both versions were strong. Worth raising the Nachos packaging consistency issue formally with GYG. The good weeks are great but the inconsistency is frustrating.$$),
    (4, '2026-04-06 18:50+10', $$Strong night. Caesar Salad was crisp and well-dressed. Chicken Enchilada was solid. Pulled pork burrito bowl was outstanding both versions — vegetarian particularly notable, jackfruit was perfectly seasoned with smoky paprika notes. Nachos arrived correctly assembled. GYG has the highest variance among our caterers — when they are on, they are the best; when off, they are the most inconsistent. Tonight was firmly on.$$),
    (4, '2026-04-13 18:50+10', $$Chicken Enchilada was the standout — outstanding cheese-to-chicken ratio, sauce had real depth. Pulled pork burrito bowl was great. Nachos were correctly assembled and crispy. Caesar Salad was on the dry side, dressing was sparse. Pulled pork burrito bowl (Vegetarian) was good, gap to non-veg narrowing again. GYG consistency improving over the past four weeks. Recommend they keep the current packaging approach.$$),
    (4, '2026-04-20 18:50+10', $$Outstanding night. Nachos were crispy and well-topped. Pulled pork burrito bowl both versions were excellent. Caesar Salad was perfect. Chicken Enchilada was hot, cheesy, well-portioned. Caesar Salad (Vegetarian) was identical in quality to the non-veg. This is GYG at its best — consistent across all dishes, correct packaging, generous portions. If they can hold this for the rest of the term, will recommend them more broadly.$$),
    (4, '2026-04-27 18:50+10', $$Pulled pork burrito bowl was excellent. Nachos slipped back to soggy assembly tonight — toppings on chips, lost crunch. Caesar Salad was good. Chicken Enchilada was over-sauced, sauce pooled at the bottom of the dish. Pulled pork burrito bowl (Vegetarian) was bland again. GYG variance continues to be the main concern — quality is there but consistency is the gap to close.$$),
    (4, '2026-05-04 18:50+10', $$Strong all-round night. Caesar Salad was crisp and well-dressed both versions. Chicken Enchilada was excellent. Pulled pork burrito bowl was great. Nachos correctly assembled. Nachos (Vegetarian) were as good as the non-veg. Pulled pork burrito bowl (Vegetarian) was finally on par with non-veg, smokiness was right. Heat retention was excellent. Best vegetarian execution we have seen from GYG this term.$$),
    (4, '2026-05-11 18:50+10', $$Mixed night. Pulled pork burrito bowl was great. Nachos were soggy. Chicken Enchilada was excellent, cheese-pull worthy. Caesar Salad was solid. Nachos (Vegetarian) and Pulled pork burrito bowl (Vegetarian) were both good. The persistent Nachos packaging issue is the single biggest barrier to GYG getting a consistent top rating from us. Otherwise quality is very high.$$),
    (4, '2026-05-18 18:50+10', $$Nachos packaging finally resolved — chips and toppings separated, served crisp. Pulled pork burrito bowl was outstanding both versions. Chicken Enchilada was perfect. Caesar Salad was crisp and generously portioned. Caesar Salad (Vegetarian) matched non-veg quality. GYG closes the term on a high — if they hold this packaging approach for Nachos, they will be a top-tier choice next term. Strong improvement trajectory over the past five weeks.$$);

-- Schools → IDs 1..4 (each assigned a caterer)
INSERT INTO schools (name, region, caterer_id) VALUES
    ('Moreton Bay Boys'' College',      'Redlands',         1),
    ('John Paul College',               'South Brisbane',   2),
    ('Indooroopilly State High School', 'West Brisbane',    3),
    ('Loreto College',                  'Central Brisbane', 4);

-- Programs → IDs 1..4 (one program per school: the weekly recurring tutoring slot)
INSERT INTO programs (school_id, day_of_week, start_time, end_time, dinner_time, building, year_levels, manager_name, manager_mobile) VALUES
    (1, 'Tuesday', '16:00', '19:00', '17:30', 'Library',       '{12,11}',      'Triet',  '0469 420 067'),
    (2, 'Tuesday', '16:30', '19:30', '18:00', 'G Centre',      '{12,11,10,9}', 'Jessie', '0412 345 678'),
    (3, 'Monday',  '15:30', '18:30', '17:00', 'X Block',       '{12,11,10,9}', 'Lucian', '0412 233 445'),
    (4, 'Monday',  '15:30', '18:30', '17:00', 'Ella Building', '{12,11,10}',   'Claire', '0488 888 888');

-- Sessions → specific dated occurrences of a program.
-- sub_manager_* populated only when the regular manager is not running that session.
INSERT INTO sessions (program_id, date, sub_manager_name, sub_manager_mobile) VALUES
    (1, '2026-05-26', NULL,    NULL),
    (1, '2026-06-02', NULL,    NULL),
    (2, '2026-05-26', 'Mia C', '0455 111 222'),
    (2, '2026-06-02', NULL,    NULL),
    (3, '2026-06-01', NULL,    NULL),
    (4, '2026-06-01', NULL,    NULL);

-- Students → IDs 1..20 (mix of dietary requirements within the GF/DF/NF/V/H enum)
-- Holly Hill and Grace Stevenson are opted out of catering (wants_catering = FALSE) to exercise that path.
-- dietary_extra is populated only when the requirement can't be expressed by the GF/DF/NF/V/H tags
-- (e.g. a specific allergy outside the enum, or a non-vegetarian eating pattern).
INSERT INTO students (name, year_level, dietary, dietary_extra, wants_catering, student_email, parent_name, parent_email, parent_mobile) VALUES
    ('Henry Hill',       11, '{}',    NULL,                                       TRUE,  'henryhill@mbbc.qld.edu.au',              'Ryan Hill',       'ryanhill@iinet.net.au',       '0478 813 748'),
    ('Noah Baker',       12, '{}',    NULL,                                       TRUE,  'noahbaker@outlook.com',                  'Eliza Baker',     'elizabaker@iinet.net.au',     '0454 745 547'),
    ('Rashid Khalil',     9, '{H,V}', NULL,                                       TRUE,  'rashidkhalil@student.jpc.qld.edu.au',    'Fatima Khalil',   'fatimakhalil@iinet.net.au',   '0487 414 081'),
    ('Benjamin Wilson',  12, '{}',    NULL,                                       TRUE,  'benjaminwilson@student.jpc.qld.edu.au',  'Aria Wilson',     'ariawilson@live.com',         '0458 480 893'),
    ('Sara Abdallah',    10, '{H}',   'No shellfish',                             TRUE,  'saraabdallah@gmail.com',                 'Samir Abdallah',  'samirabdallah@live.com',      '0411 229 871'),
    ('Sophie Harris',    12, '{V}',   NULL,                                       TRUE,  'sophieharris@eq.edu.au',                 'Tristan Harris',  'tristanharris@hotmail.com',   '0421 889 323'),
    ('Holly Hill',       10, '{}',    NULL,                                       FALSE, 'hollyhill@gmail.com',                    'Benjamin Hill',   'benjaminhill@yahoo.com',      '0445 718 173'),
    ('Matilda Turner',   11, '{DF}',  NULL,                                       TRUE,  'matildaturner@loreto.qld.edu.au',        'Phoebe Turner',   'phoebeturner@yahoo.com',      '0467 957 174'),
    ('Oliver Bennett',   11, '{GF}',  NULL,                                       TRUE,  'oliverbennett@mbbc.qld.edu.au',          'Megan Bennett',   'meganbennett@outlook.com',    '0432 118 909'),
    ('Leo Marsh',        12, '{V}',   NULL,                                       TRUE,  'leomarsh@mbbc.qld.edu.au',               'Diana Marsh',     'dianamarsh@iinet.net.au',     '0498 332 415'),
    ('Ethan Mitchell',   11, '{NF}',  NULL,                                       TRUE,  'ethanmitchell@mbbc.qld.edu.au',          'Nina Mitchell',   'ninamitchell@gmail.com',      '0419 776 224'),
    ('Aisha Khan',       10, '{H}',   'Severe egg allergy',                       TRUE,  'aishakhan@student.jpc.qld.edu.au',       'Yasmin Khan',     'yasminkhan@hotmail.com',      '0488 102 553'),
    ('Lucas Nguyen',      9, '{}',    NULL,                                       TRUE,  'lucasnguyen@student.jpc.qld.edu.au',     'Minh Nguyen',     'minhnguyen@outlook.com',      '0426 519 880'),
    ('Mia Chen',         12, '{}',    'Pescatarian — fish only, no other meat',   TRUE,  'miachen@student.jpc.qld.edu.au',         'Hua Chen',        'huachen@gmail.com',           '0461 778 092'),
    ('Tom Whitfield',    11, '{DF}',  NULL,                                       TRUE,  'tomwhitfield@student.jpc.qld.edu.au',    'Greg Whitfield',  'gregwhitfield@iinet.net.au',  '0407 224 631'),
    ('Jackson O''Brien',  9, '{}',    NULL,                                       TRUE,  'jacksonobrien@eq.edu.au',                'Sean O''Brien',   'seanobrien@live.com',         '0421 045 992'),
    ('Ava Robinson',     11, '{DF}',  NULL,                                       TRUE,  'avarobinson@eq.edu.au',                  'Holly Robinson',  'hollyrobinson@yahoo.com',     '0418 663 207'),
    ('Liam Kowalski',    10, '{GF}',  NULL,                                       TRUE,  'liamkowalski@eq.edu.au',                 'Petra Kowalski',  'petrakowalski@outlook.com',   '0432 891 116'),
    ('Isla Thompson',    12, '{V,H}', NULL,                                       TRUE,  'islathompson@loreto.qld.edu.au',         'Claire Thompson', 'clairethompson@gmail.com',    '0429 553 110'),
    ('Grace Stevenson',  10, '{}',    NULL,                                       FALSE, 'gracestevenson@loreto.qld.edu.au',       'Adam Stevenson',  'adamstevenson@live.com',      '0455 002 174');

-- Enrolments (student → program: the weekly slot they signed up for)
INSERT INTO enrolments (student_id, program_id) VALUES
    -- Moreton Bay (program 1)
    (1, 1), (2, 1), (9, 1), (10, 1), (11, 1),
    -- John Paul College (program 2)
    (3, 2), (4, 2), (12, 2), (13, 2), (14, 2), (15, 2),
    -- Indooroopilly (program 3)
    (5, 3), (6, 3), (16, 3), (17, 3), (18, 3),
    -- Loreto (program 4)
    (7, 4), (8, 4), (19, 4), (20, 4);

-- Absences: students who won't be at a specific dated session of their program.
INSERT INTO absences (student_id, program_id, date) VALUES
    (2, 1, '2026-06-02'),  -- Noah Baker missing the second Moreton Bay session
    (5, 3, '2026-06-01');  -- Sara Abdallah missing Indooroopilly on 1 June
